### ISSUE TITLE
License查询列表

### ISSUE THREAD

**Issue by zejun19** [opensourceways/sbom-website#29]
在以下截图出，点击后页内弹框，显示License信息列表

![image](https://user-images.githubusercontent.com/86641897/195823045-91617d00-39ea-4403-b0dd-7ae52a256e7a.png)
![image](https://user-images.githubusercontent.com/86641897/195823101-68dd571a-4e92-4119-93a0-6323a0f2e3f6.png)

**Comment by ZXF982214487** [comment]
[https://github.com/opensourceways/sbom-service/blob/main/doc/api/%E6%9F%A5%E8%AF%A2%E5%88%B6%E5%93%81license%E8%AF%A6%E6%83%85.md](查询制品license文档)

**Comment by zejun19** [comment]
![image](https://user-images.githubusercontent.com/86641897/199669323-1ef5a049-f818-44cc-b542-62d197c4512a.png)

列显示值使用licenseId字段，悬浮使用licenseName字段

**Comment by zejun19** [comment]
饼图弹框需修改

**Comment by zejun19** [comment]
> 饼图弹框需修改

已修改

**Comment by zejun19** [comment]
> ![image](https://user-images.githubusercontent.com/86641897/199669323-1ef5a049-f818-44cc-b542-62d197c4512a.png)
> 
> 列显示值使用licenseId字段，悬浮使用licenseName字段

已修改

**Comment by zejun19** [comment]
@liting0916 
无链接的A标签样式修改

**Comment by zejun19** [comment]
> @liting0916 无链接的A标签样式修改

修改

**Comment by zejun19** [comment]
![image](https://user-images.githubusercontent.com/86641897/200726432-06ed068b-e07a-48c2-a7bc-e4d27200cf25.png)

按License名字排序

**Comment by zejun19** [comment]
![image](https://user-images.githubusercontent.com/86641897/200726796-48c35978-f26e-4f77-88d7-2772ccfbe423.png)

1. 按License数量排序
2. 饼图上除“其他”以为，都传递参数：license id（饼图查询结果中国的licenseId）

**Comment by zejun19** [comment]
翻页有问题，始终是第一页

**Comment by ZXF982214487** [comment]
![image](https://user-images.githubusercontent.com/28819794/201810339-e181b887-b93b-47e5-bdef-69fce33a63b1.png)

点击“其他”按钮时，不传license参数，把所有license显示出来
