### ISSUE TITLE
更换包详情页面里的漏洞详情查询接口

### ISSUE THREAD

**Issue by huanceng** [opensourceways/sbom-website#35]
![image](https://user-images.githubusercontent.com/14803898/196937551-f9955c57-0443-43b7-a63e-5846b74d42a2.png)

~~在[#26](https://github.com/opensourceways/sbom-website/issues/26)需求中，后端统一了漏洞详情查询接口，原来调用的/queryPackageVulnerability接口统一替换为/queryVulnerability。
[接口文档](https://github.com/opensourceways/sbom-service/blob/main/doc/api/%E6%9F%A5%E8%AF%A2%E6%BC%8F%E6%B4%9E%E8%AF%A6%E6%83%85.md)~~

由于统计原因，本页的漏洞信息查询接口改回：[接口文档](https://github.com/opensourceways/sbom-service/blob/main/doc/api/%E6%9F%A5%E8%AF%A2%E8%BD%AF%E4%BB%B6%E5%8C%85%E6%BC%8F%E6%B4%9E%E8%AF%A6%E6%83%85.md)

**Comment by zejun19** [comment]
后端原有接口删除

**Comment by zejun19** [comment]
@huanceng 
验证数据
