### ISSUE TITLE
首次进入自动触发表单校验

### ISSUE THREAD

**Issue by zejun19** [opensourceways/sbom-website#38]
![image](https://user-images.githubusercontent.com/86641897/200282413-00fb6ebf-0556-4d76-bff3-e0c8469a5034.png)

![image](https://user-images.githubusercontent.com/86641897/200282461-572000ba-4635-4377-80d2-07c0fe2d5581.png)

首次进入自动触发表单校验，应该不需要在首次未输入时触发表单校验；提高使用体验

**Comment by zejun19** [comment]
本地开发模式不能复现

**Comment by huanceng** [comment]
#52已修改选择逻辑
