### ISSUE TITLE
风险看板漏洞组件统计的“低”风险漏洞组件数据错误

### ISSUE THREAD

**Issue by huanceng** [opensourceways/sbom-website#39]
![image](https://user-images.githubusercontent.com/14803898/200465725-c152aeb2-0d28-4d0c-9dfc-b15ee96cbc99.png)
![image](https://user-images.githubusercontent.com/14803898/200465740-de48e2aa-d350-42db-9fd3-15418faef72c.png)
取packageWithLowVulCount的值，应该为3，实际页面显示0

**Comment by zejun19** [comment]
已修复
