### ISSUE TITLE
社区名称从支持majun传递

### ISSUE THREAD

**Issue by zejun19** [opensourceways/sbom-website#42]
社区名称从支持majun传递
P.S.  还需要同时支持SBOM独立站点的场景（没有社区名称的传值）

**Comment by zejun19** [comment]
SBOM单独访问正常，待Majun集成环境上线后再做集成测试

**Comment by huanceng** [comment]
![image](https://user-images.githubusercontent.com/14803898/208365982-8370548c-330c-4e63-a7a4-6f2dfa4b143c.png)
从MaJun传递社区名称时，不展示其他社区选项，当前是置灰
