### ISSUE TITLE
"制品统计信息不存在"场景优化

### ISSUE THREAD

**Issue by huanceng** [opensourceways/sbom-website#54]
![image](https://user-images.githubusercontent.com/14803898/203047131-dd544b6a-897a-4e02-a964-29c1a712a354.png)

1. "制品统计信息不存在"时，需要弹窗提示；
2. 选择一个有统计信息的制品后，再选择另一个没有统计信息的制品，页面上的统计信息需要清除

**Comment by zejun19** [comment]
已解决
