### ISSUE TITLE
软件成分数据中license字段修改

### ISSUE THREAD

**Issue by ZXF982214487** [opensourceways/sbom-website#66]
sbom-api/querySbomPackages接口返回字段已修改
其中licenseConcluded （String） 字段修改为 licenses (List<String>)
具体查看[查询制品软件包列表](https://github.com/opensourceways/sbom-service/blob/main/doc/api/%E6%9F%A5%E8%AF%A2%E5%88%B6%E5%93%81%E8%BD%AF%E4%BB%B6%E5%8C%85%E5%88%97%E8%A1%A8.md)

**Comment by ZXF982214487** [comment]
前端界面需要对接口修改后的返回数据适配展示

**Comment by zejun19** [comment]
之前licenseConcluded 是string字段，由前端根据and进行拆分多个license；新的licenses为数组string，已预拆分好，直接展示即可
